apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-lab
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  liveness:
    path: /actuator/health
  readiness:
    path: /actuator/health
  ingresses:
    - https://omsorgspenger-lab.dev.intern.nav.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90