name: Bygg og deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Kjør tester & bygg JAR
        run: |
          ./gradlew test shadowjar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sett tag for docker
        run: echo "IMAGE=${REGISTRY}:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        env:
          REGISTRY: ghcr.io/${{ github.repository }}

      - name: Bygg & last opp Docker image
        run: |
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}

      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/naiserator.yaml